const citiesList = [
  {label: 'New York', value: 'New York'},
  {label: 'Los Angeles', value: 'Los Angeles'},
  {label: 'Chicago', value: 'Chicago'},
  {label: 'Houston', value: 'Houston'},
  {label: 'Phoenix', value: 'Phoenix'},
  {label: 'Philadelphia', value: 'Philadelphia'},
  {label: 'San Antonio', value: 'San Antonio'},
  {label: 'San Diego', value: 'San Diego'},
  {label: 'Dallas', value: 'Dallas'},
  {label: 'San Jose', value: 'San Jose'},
  {label: 'Austin', value: 'Austin'},
  {label: 'Jacksonville', value: 'Jacksonville'},
  {label: 'Indianapolis', value: 'Indianapolis'},
  {label: 'San Francisco', value: 'San Francisco'},
  {label: 'Columbus', value: 'Columbus'},
  {label: 'Fort Worth', value: 'Fort Worth'},
  {label: 'Charlotte', value: 'Charlotte'},
  {label: 'Seattle', value: 'Seattle'},
  {label: 'Denver', value: 'Denver'},
  {label: 'El Paso', value: 'El Paso'},
  {label: 'Detroit', value: 'Detroit'},
  {label: 'Washington', value: 'Washington'},
  {label: 'Boston', value: 'Boston'},
  {label: 'Memphis', value: 'Memphis'},
  {label: 'Nashville', value: 'Nashville'},
  {label: 'Portland', value: 'Portland'},
  {label: 'Oklahoma City', value: 'Oklahoma City'},
  {label: 'Las Vegas', value: 'Las Vegas'},
  {label: 'Louisville', value: 'Louisville'},
  {label: 'Baltimore', value: 'Baltimore'},
  {label: 'Milwaukee', value: 'Milwaukee'},
  {label: 'Albuquerque', value: 'Albuquerque'},
  {label: 'Tucson', value: 'Tucson'},
  {label: 'Fresno', value: 'Fresno'},
  {label: 'Sacramento', value: 'Sacramento'},
  {label: 'Mesa', value: 'Mesa'},
  {label: 'Kansas City', value: 'Kansas City'},
  {label: 'Atlanta', value: 'Atlanta'},
];

export default citiesList;
